household_power_consumption <- read.csv("~/Downloads/household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE, nrows=10)
household_power_consumption <- read.csv("~/Downloads/household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE, colClasses = sapply(household_power_consumption, class))
household_power_consumption$Date <- as.Date(household_power_consumption$Date, format="%d/%m/%Y")
household_power_consumption <- subset(household_power_consumption, Date == "2007-02-01" | Date == "2007-02-02")
household_power_consumption$Timestamp <- as.POSIXct(paste(household_power_consumption$Date, household_power_consumption$Time), format="%Y-%m-%d %H:%M:%S")
png(file="plot3.png", width=480, height=480)
with(household_power_consumption, plot(Timestamp, Sub_metering_1, type="l", ylab="Energy sub metering", xlab=""))
with(household_power_consumption, lines(Timestamp, Sub_metering_2, col="red", xlab=""))
with(household_power_consumption, lines(Timestamp, Sub_metering_3, col="blue", xlab=""))
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1), col=c("black", "red", "blue"))
dev.off()